#!/bin/bash

while true
do

clear

echo "=========================================="
echo "		SOC TOOLKIT v1"
echo "		By Mehul Parmar"
echo "=========================================="
echo""

echo "1. System Information"
echo "2. Log Monitor"
echo "3. Ping Host"
echo "4. Process Moniter"
echo "5. Network Information"
echo "6. User Information"
echo "7. File Permission Checker"
echo "8. Save Report"
echo "9. Exit"
echo ""

read -p "Enter your choice: " choice

case $choice in

1)
	echo""
	echo "====== SYSTEM INFORMATION ======"
	hostname
	whoami
	uname -r
	uptime

	echo ""
	read -p "Press Enter to Continue..."
	;;

2)
	echo ""
	echo "======LOG MONITOR ======"
	journalctl -n 10 --no-pager

	echo ""
        read -p "Press Enter to Continue..."
	;;


3)
	echo""
	read -p "Enter IP or Domain:" Domain

	echo "====== PING HOST ======"
	ping -c 4 "$Domain"

	echo ""
	read -p "Press Enter to Continue..."
	;;


4)
	echo ""
	echo "====== PROCESS MONITOR ======="
	ps aux | head

	echo ""
        read -p "Press Enter to Continue..."
	;;

5)
	echo ""
	echo "====== NETWORK INFORMATION ======"


	echo "[+] Hostname"
	hostname

	echo ""
	echo "[+] IP Address"
	ip a

	echo ""
	echo "[+]Routing Table "
	ip route

	echo ""
	echo "[+] Listening Ports"
	ss -tuln

	echo ""
        read -p "Press Enter to Continue..."
	;;


6)

	echo "====== USER INFORMATON ======"

	echo ""
	echo "[+] Current User"
	whoami

	echo ""
	echo "[+] User ID"
	id

	echo ""
	echo "[+] Groups"
	groups

	echo ""
	echo "[+] Logged In Users"
	who

	echo ""
	echo "[+] Login History"
	last | head

	echo ""
	read -p "Press  Enter to Continue..."

	;;


7)
	echo "====== FILE PERMISSION CHECKER ======"

	echo ""
	read -p "Enter File name: " file

	echo "Current Directory:"
	pwd
	ls

	echo "You Entered: $file"

	if [ -e "$file" ]; then

		echo ""
		echo "[+] File Details"

		ls -lh  "$file"

		echo ""
		echo "[+] Detailed Information"

		stat "$file"

	else

		echo ""
		echo "File not Found!"

	fi

	echo ""
	read -p "Press Enter to continue..."

	echo "Current Directiory:"
	pwd

	echo " You Entered: $file"

	;;

8)

	echo "Generating Report..."
	read -p "Enter Report Name:" report

	{

	echo ""
	     "======================================"
	echo "		SOC TOOLKIT REPORT"
	echo "	Generated by : Mehul Parmar"
	echo "	Date  : $(date +%F)"
	echo "	Time  : $(date +%T)"
	echo
	     "======================================"
	echo ""

	echo "[System Information]"
	echo "Hostname	:	$(hostname)"
	echo "Username 	:	$(whoami)"
	echo "kernel 	: 	$(uname -r)"
	echo "Uptime	:	$(uptime -p)"
	echo

	echo "[Network Information]"
	echo "IP Address:"
	hostname -I

	echo
	echo "Gateway"
	ip route | grep default

	echo
	echo "Listening Ports:"
	ss -tuln
	echo

	echo "[User Information]"
	echo "Current User:"
	whoami

	echo
	echo "User ID:"
	id

	echo
	echo "Groups:"
	groups

	echo
	echo "Logged In Users:"
	who
	echo

	echo "[Processes Information]"
	echo "[Top 10 Processes]"
	ps aux | head -10
	echo

	echo "[Disk Information]"
	echo "[Disk Usage]"
	df -h
	echo

	echo "[Memory Information]"
	echo "[Memory Usage]"
	free -h
	echo

	} > "${report}.txt"

	echo ""
	echo "Report Saved Successfully!"
	echo "File Name : ${report}.txt"

	;;


9)
	echo  "Thank you for using SOC Toolkit."
	break
	;;

*)
	echo "Invalid Choice"

	echo ""
        read -p "Press Enter to Continue..."
	;;

esac

done
