#!/bin/bash

#============================================================
# SOC Toolkit v1.0
# Version		: 1.0.0
# Developer	: Mehul Parmar
# Description	: Menu-driven Linux SOC Toolkit 
# License		: MIT
#============================================================

# Main program loop
while true
do

clear

echo "======================================================"
echo "	SOC TOOLKIT v1.0"
echo "Developer 	: By Mehul Parmar"
echo "Description 	: Menu-driven Linux  SOC Toolkit"
echo "======================================================"
echo

# Display Main Menu
echo "1. System Information"
echo "2. Log Monitor"
echo "3. Ping Host"
echo "4. Process Monitor"
echo "5. Network Information"
echo "6. User Information"
echo "7. File Permission Checker"
echo "8. Save Report"
echo "9. Exit"
echo

read -p "Enter your choice: " choice

# Handle user menu selection
case $choice in

# Option 1 - Display System Information
1)
	echo
	echo "====== [SYSTEM INFORMATION] ======"
	hostname
	whoami
	uname -r
	uptime

	echo
	read -p "Press Enter to Continue..."
	;;

# Option 2 - Show Recent System Logs
2)
	echo
	echo "====== [LOG MONITOR] ======"
	journalctl -n 10 --no-pager

	echo
        read -p "Press Enter to Continue..."
	;;

# Option 3 - Ping Host
3)
	echo
	read -p "Enter IP or Domain: " domain

	echo "====== [PING HOST] ======"
	ping -c 4 "$domain"

	echo
	read -p "Press Enter to Continue..."
	;;

# Option 4 - Process Monitor Information
4)
	echo
	echo "====== [PROCESS MONITOR] ======"
	ps aux | head -11

	echo
        read -p "Press Enter to Continue..."
	;;

# Option 5 - Network Information
5)
	echo
	echo "====== [NETWORK INFORMATION] ======"

	echo "[+] Hostname"
	hostname

	echo
	echo "[+] IP Address"
	ip a

	echo
	echo "[+] Routing Table"
	ip route

	echo
	echo "[+] Listening Ports"
	ss -tuln

	echo
        read -p "Press Enter to Continue..."
	;;

# Option 6 - User Information
6)

	echo "====== [USER INFORMATION] ======"

	echo
	echo "[+] Current User"
	whoami

	echo
	echo "[+] User ID"
	id

	echo
	echo "[+] Groups"
	groups

	echo
	echo "[+] Logged In Users"
	who

	echo
	echo "[+] Login History"
	last | head

	echo
	read -p "Press Enter to Continue..."

	;;

# Option 7 - File Permission CHECKER
7)
	echo "====== [FILE PERMISSION CHECKER] ======"

	echo
	read -p "Enter File name: " file

	if [ -e "$file" ]; then

		echo
		echo "[+] File Details"

		ls -lh  "$file"

		echo
		echo "[+] Detailed Information"

		stat "$file"

	else

		echo
		echo "File not Found!"

	fi

	echo
	read -p "Press Enter to continue..."
	;;

# Option 8  Generate SOC Report
8)

	echo "Generating Report..."
	read -p "Enter Report Name: " report

	if [ -z "$report" ]; then
		report="SOC_Report"
	fi
	{

	echo "======================================"
	echo "		[SOC TOOLKIT REPORT]"
	echo "	Generated by 	: Mehul Parmar"
	echo "	Date  		: $(date +%F)"
	echo "	Time  		: $(date +%T)"
	echo "======================================"
	echo

	echo "[System Information]"
	echo "Hostname	:	$(hostname)"
	echo "Username 	:	$(whoami)"
	echo "Kernel 	: 	$(uname -r)"
	echo "Uptime	:	$(uptime -p)"
	echo

	echo "[Network Information]"
	echo "IP Address:"
	hostname -I

	echo
	echo "Gateway"
	ip route | grep default

	echo
	echo "Listening Ports:"
	ss -tuln
	echo

	echo "[User Information]"
	echo "Current User:"
	whoami

	echo
	echo "User ID:"
	id

	echo
	echo "Groups:"
	groups

	echo
	echo "Logged In Users:"
	who
	echo

	echo "[Processes Information]"
	echo "Top 10 Processes"
	ps aux | head -11
	echo

	echo "[Disk Information]"
	echo "Disk Usage"
	df -h
	echo

	echo "[Memory Information]"
	echo "Memory Usage"
	free -h
	echo

	} > "${report}.txt"

	echo
	echo "Report Saved Successfully!"
	echo "File Name : ${report}.txt"

	;;


# Option 9 - Exit Toolkit
9)
	echo
	echo  "Thank you for using SOC Toolkit."
	echo "Goodbye!"
	break
	;;

*)
	echo "[!] Invalid Choice"

	echo
        read -p "Press Enter to Continue..."
	;;

esac
done
